/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AdConversionStatus = "failed" | "queued" | "sent" | "skipped";

export type ApprovalStatus = "approved" | "expired" | "pending" | "rejected";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type CampaignStatus = "approved" | "cancelled" | "draft" | "pending_approval" | "scheduled" | "sending" | "sent";

export type ConnectionStatus = "connected" | "pending" | "revoked" | "unhealthy";

export type ConsentPurpose = "ad_platform_sharing" | "card_recognition" | "marketing_email" | "marketing_sms";

export type ConsentStatus = "granted" | "revoked";

export type CustomerStatus = "active" | "deleted" | "merged";

export type DeliveryStatus = "cancelled" | "courier_assigned" | "delivered" | "failed" | "picked_up" | "quoted" | "requested" | "returned";

export type DevicePurpose = "counter" | "kitchen";

export type DiscountKind = "fixed" | "free_item" | "percent";

export type EnrollmentStatus = "active" | "cancelled" | "completed" | "exited";

export type EventSource = "agent" | "comms" | "import" | "pos" | "server" | "web";

export type FlowMode = "autonomous" | "off" | "shadow" | "supervised";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type IdentityKind = "card_fingerprint" | "card_par" | "device_id" | "email" | "loyalty_qr" | "phone" | "pos_customer_id";

export type JobStatus = "dead" | "failed" | "queued" | "running" | "succeeded";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LoyaltyTxnKind = "adjust" | "bonus" | "burn" | "earn" | "expire" | "reverse" | "transfer";

export type MsgChannel = "email" | "sms";

export type MsgKind = "marketing" | "transactional";

export type MsgStatus = "bounced" | "cancelled" | "delivered" | "failed" | "queued" | "sending" | "sent" | "suppressed";

export type Numeric = ColumnType<number, number | string, number | string>;

export type OfferCodeStatus = "claimed" | "expired" | "issued" | "redeemed" | "voided";

export type OfferKind = "birthday" | "comeback" | "creator" | "manual" | "voucher" | "welcome";

export type OnboardingOrigin = "platform" | "self_serve";

export type OrderChannel = "delivery" | "dine-in-qr" | "pickup";

export type OrderPaymentStatus = "failed" | "paid" | "partially_refunded" | "refunded" | "unpaid";

export type OrderStatus = "accepted" | "cancelled" | "completed" | "draft" | "pending_payment" | "placed" | "preparing" | "ready" | "refunded" | "rejected";

export type OrgStatus = "closed" | "live" | "onboarding" | "paused";

export type OtpPurpose = "guest_login" | "platform_login" | "staff_login";

export type PaymentStatus = "completed" | "failed" | "partially_refunded" | "pending" | "refunded";

export type QrKind = "campaign" | "counter" | "menu" | "table";

export type RedemptionChannel = "counter" | "online";

export type RedemptionStatus = "expired" | "issued" | "redeemed" | "voided";

export type ReviewDraftAuthor = "agent" | "assistant" | "staff";

export type ReviewDraftStatus = "approved" | "blocked" | "failed" | "pending" | "posted" | "rejected" | "shadow";

export type ReviewReplyStatus = "drafted" | "failed" | "none" | "pending_approval" | "posted";

export type SelectionType = "multi" | "single";

export type SessionKind = "guest" | "platform" | "staff";

export type SideEffectStatus = "failed" | "started" | "succeeded";

export type StaffRole = "front_of_house" | "host" | "kitchen" | "manager" | "owner" | "read_only";

export type StaffStatus = "active" | "disabled" | "invited";

export type SuppressionReason = "bounced_hard" | "complained" | "manual" | "unsubscribed";

export type TicketStatus = "acknowledged" | "bumped" | "cancelled" | "new" | "ready";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TxnChannel = "catering" | "delivery" | "dine-in" | "pickup" | "retail";

export type TxnSource = "aggregator" | "lightspeed" | "manual" | "online-order" | "pos" | "sim" | "square";

export type TxnStatus = "completed" | "partially_refunded" | "pending" | "refunded" | "voided";

export type VenueStatus = "closed" | "live" | "paused" | "setup";

export interface AdConversions {
  connection_id: string;
  created_at: Generated<Timestamp>;
  currency: string;
  customer_id: string | null;
  event_id: string;
  id: Generated<string>;
  org_id: string;
  reason: string | null;
  sent_at: Timestamp | null;
  source: string;
  status: Generated<AdConversionStatus>;
  transaction_id: string;
  updated_at: Generated<Timestamp>;
  value_cents: number;
  venue_id: string;
}

export interface AgentCalls {
  actor_kind: Generated<string>;
  agent_run_id: string | null;
  duration_ms: number | null;
  effect: string;
  hosted_agent_key: string | null;
  id: Generated<string>;
  key_id: string | null;
  occurred_at: Generated<Timestamp>;
  org_id: string;
  outcome: string;
  plug_key: Generated<string>;
  tool: string;
}

export interface AgentConfirmations {
  args_digest: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  key_id: string;
  nonce: string;
  org_id: string;
  question_digest: string;
  spent_at: Timestamp | null;
  tool: string;
}

export interface AgentKeys {
  audience: Generated<string>;
  can_write: Generated<boolean>;
  connection_id: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  key_hash: Buffer;
  key_prefix: string;
  kind: Generated<string>;
  last_used_at: Timestamp | null;
  name: string;
  oauth_client_id: string | null;
  org_id: string;
  revoked_at: Timestamp | null;
  scopes: Generated<string[]>;
  staff_id: string;
  venue_ids: string[] | null;
}

export interface AgentOauthClients {
  client_id: string;
  client_name: string;
  client_uri: string | null;
  created_at: Generated<Timestamp>;
  last_used_at: Timestamp | null;
  redirect_uris: string[];
}

export interface AgentOauthCodes {
  can_write: Generated<boolean>;
  client_id: string;
  client_name: string;
  code_challenge: string;
  code_hash: Buffer;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  key_id: string | null;
  lasts_days: number;
  org_id: string;
  redirect_uri: string;
  resource: string;
  scopes: string[];
  staff_id: string;
  used_at: Timestamp | null;
  venue_ids: string[] | null;
}

export interface AgentOauthTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  key_id: string;
  kind: string;
  org_id: string;
  resource: string;
  token_hash: Buffer;
  used_at: Timestamp | null;
}

export interface AgentRuns {
  agent_key: string;
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  mode: FlowMode;
  org_id: string;
  output: Json | null;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
  summary: string | null;
  template_version: string;
  tokens_in: number | null;
  tokens_out: number | null;
  trigger: string;
  venue_id: string | null;
}

export interface Approvals {
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by_staff_id: string | null;
  decision_note: string | null;
  expires_at: Timestamp | null;
  id: Generated<string>;
  kind: string;
  org_id: string;
  payload: Generated<Json>;
  requested_by_id: string | null;
  requested_by_kind: string;
  status: Generated<ApprovalStatus>;
  subject_id: string;
  subject_type: string;
  summary: string;
  venue_id: string | null;
}

export interface AuditLog {
  action: string;
  actor_id: string | null;
  actor_kind: string;
  after: Json | null;
  before: Json | null;
  entity_id: string | null;
  entity_type: string;
  id: Generated<string>;
  ip: string | null;
  occurred_at: Generated<Timestamp>;
  org_id: string;
  request_id: string | null;
  venue_id: string | null;
}

export interface BenchmarkBands {
  cohort: string;
  computed_at: Generated<Timestamp>;
  id: Generated<string>;
  metric: string;
  n_orgs: number;
  p25: Numeric | null;
  p50: Numeric | null;
  p75: Numeric | null;
  period_end: string;
  period_start: string;
}

export interface Brands {
  id: Generated<string>;
  layout_skeleton: Generated<string>;
  logo_mark_url: string | null;
  logo_raster_url: string | null;
  logo_svg_url: string | null;
  org_id: string;
  tokens: Generated<Json>;
  tone_of_voice: string | null;
  updated_at: Generated<Timestamp>;
  venue_id: string | null;
}

export interface Campaigns {
  approved_by_staff_id: string | null;
  audience_count: number | null;
  body: string | null;
  channel: MsgChannel;
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  created_by_kind: Generated<string>;
  id: Generated<string>;
  name: string;
  offer_id: string | null;
  org_id: string;
  scheduled_at: Timestamp | null;
  segment_id: string | null;
  sent_at: Timestamp | null;
  stats: Generated<Json>;
  status: Generated<CampaignStatus>;
  subject: string | null;
  template_key: string | null;
  updated_at: Generated<Timestamp>;
  venue_id: string | null;
}

export interface Connections {
  config: Generated<Json>;
  connected_at: Timestamp | null;
  connected_by_staff_id: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  external_account_id: Generated<string>;
  id: Generated<string>;
  last_error: string | null;
  last_ok_at: Timestamp | null;
  org_id: string;
  plug_key: string;
  scopes: Generated<string[]>;
  secret_ref: string | null;
  status: Generated<ConnectionStatus>;
  updated_at: Generated<Timestamp>;
  venue_id: string | null;
}

export interface ConsentEvents {
  action: ConsentStatus;
  customer_id: string;
  id: Generated<string>;
  ip: string | null;
  occurred_at: Generated<Timestamp>;
  org_id: string;
  purpose: ConsentPurpose;
  source: string;
  source_detail: string | null;
  wording_version: string;
}

export interface Consents {
  consented_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  customer_id: string;
  id: Generated<string>;
  ip: string | null;
  org_id: string;
  purpose: ConsentPurpose;
  revoked_at: Timestamp | null;
  source: string;
  source_detail: string | null;
  status: ConsentStatus;
  updated_at: Generated<Timestamp>;
  wording_version: string;
}

export interface ConsentWordings {
  body: string;
  effective_from: Generated<Timestamp>;
  id: Generated<string>;
  org_id: string | null;
  purpose: ConsentPurpose;
  version: string;
}

export interface CustomerIdentities {
  created_at: Generated<Timestamp>;
  customer_id: string;
  id: Generated<string>;
  kind: IdentityKind;
  org_id: string;
  source: string | null;
  value: string;
  verified_at: Timestamp | null;
}

export interface CustomerMerges {
  id: Generated<string>;
  loser_customer_id: string;
  merged_at: Generated<Timestamp>;
  merged_by: string | null;
  org_id: string;
  reason: string | null;
  winner_customer_id: string;
}

export interface Customers {
  acquisition_at: Generated<Timestamp>;
  acquisition_campaign_id: string | null;
  acquisition_code: string | null;
  acquisition_creator_id: string | null;
  acquisition_landing_path: string | null;
  acquisition_qr_code_id: string | null;
  acquisition_source: Generated<string>;
  allergy_notes: string | null;
  birthday: string | null;
  created_at: Generated<Timestamp>;
  first_name: string | null;
  first_seen_venue_id: string | null;
  id: Generated<string>;
  last_name: string | null;
  merged_into_id: string | null;
  notes: string | null;
  org_id: string;
  primary_email: string | null;
  primary_phone: string | null;
  status: Generated<CustomerStatus>;
  updated_at: Generated<Timestamp>;
}

export interface CustomerTouchpoints {
  campaign_id: string | null;
  channel: string;
  code: string | null;
  creator_id: string | null;
  customer_id: string;
  id: Generated<string>;
  metadata: Generated<Json>;
  occurred_at: Generated<Timestamp>;
  org_id: string;
}

export interface Deliveries {
  attempted_providers: Generated<string[]>;
  cancellation_fee_cents: Generated<number>;
  connection_id: string | null;
  contains_alcohol: Generated<boolean>;
  courier_fee_cents: Generated<number>;
  courier_name: string | null;
  created_at: Generated<Timestamp>;
  customer_fee_cents: Generated<number>;
  customer_id: string | null;
  delivered_at: Timestamp | null;
  dropoff_address: Json;
  dropoff_eta: Timestamp | null;
  dropoff_lat: number | null;
  dropoff_lng: number | null;
  dropoff_notes: string | null;
  external_ref: string | null;
  failure_reason: string | null;
  id: Generated<string>;
  idempotency_key: string;
  last_checked_at: Timestamp | null;
  order_id: string | null;
  order_value_cents: Generated<number>;
  org_id: string;
  pickup_eta: Timestamp | null;
  proof: Json | null;
  provider: string;
  quote_expires_at: Timestamp | null;
  quote_id: string | null;
  request_at: Timestamp | null;
  requested_at: Timestamp | null;
  status: Generated<DeliveryStatus>;
  tracking_url: string | null;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface DeliveryStatusHistory {
  at: Generated<Timestamp>;
  delivery_id: string;
  from_status: DeliveryStatus | null;
  id: Generated<string>;
  org_id: string;
  raw: Json | null;
  source: string;
  to_status: DeliveryStatus;
}

export interface DeliveryZones {
  created_at: Generated<Timestamp>;
  fee_rule: Generated<Json>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: Generated<string>;
  min_order_cents: Generated<number>;
  name: string;
  org_id: string;
  polygon: Json | null;
  radius_m: number | null;
  venue_id: string;
}

export interface Devices {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_seen_at: Timestamp | null;
  name: string;
  org_id: string;
  paired_at: Timestamp | null;
  pairing_code_hash: Buffer | null;
  pairing_expires_at: Timestamp | null;
  purpose: DevicePurpose;
  revoked_at: Timestamp | null;
  token_hash: Buffer | null;
  venue_id: string;
}

export interface Domains {
  created_at: Generated<Timestamp>;
  host: string;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  kind: Generated<string>;
  org_id: string;
  provider_domain_id: string | null;
  venue_id: string | null;
  verified_at: Timestamp | null;
}

export interface EspSyncProfiles {
  connection_id: string;
  customer_id: string;
  digest: string;
  org_id: string;
  pushed_at: Timestamp;
  state: string;
}

export interface EspSyncState {
  connection_id: string;
  last_counts: Json | null;
  last_error: string | null;
  last_ok_at: Timestamp | null;
  last_run_at: Timestamp | null;
  orders_through: Timestamp | null;
  org_id: string;
  points_through: Timestamp | null;
  profiles_through: Timestamp | null;
  suppressions_pulled_through: Timestamp | null;
  suppressions_pushed_through: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface Events {
  campaign_id: string | null;
  code: string | null;
  creator_id: string | null;
  customer_id: string | null;
  id: Generated<string>;
  name: string;
  occurred_at: Generated<Timestamp>;
  org_id: string;
  properties: Generated<Json>;
  session_id: string | null;
  source: Generated<EventSource>;
  utm_campaign: string | null;
  utm_medium: string | null;
  utm_source: string | null;
  venue_id: string | null;
}

export interface FactCampaignDaily {
  campaign_id: Generated<string>;
  channel: Generated<string>;
  computed_at: Generated<Timestamp>;
  creator_id: Generated<string>;
  day: string;
  new_customers: Generated<number>;
  orders: Generated<number>;
  org_id: string;
  repeat_orders: Generated<number>;
  revenue_cents: Generated<number>;
  sessions: Generated<number>;
  venue_key: Generated<string>;
}

export interface FactCustomer {
  avg_order_cents: Generated<number>;
  computed_at: Generated<Timestamp>;
  customer_id: string;
  days_to_second_order: number | null;
  f_score: number | null;
  favourite_channel: TxnChannel | null;
  favourite_venue_id: string | null;
  first_order_at: Timestamp | null;
  first_order_day: string | null;
  last_order_at: Timestamp | null;
  last_order_day: string | null;
  m_score: number | null;
  orders: Generated<number>;
  org_id: string;
  r_score: number | null;
  recency_days: number | null;
  second_order_at: Timestamp | null;
  segment: string | null;
  spend_cents: Generated<number>;
}

export interface FactEventsDaily {
  campaign_id: Generated<string>;
  computed_at: Generated<Timestamp>;
  creator_id: Generated<string>;
  customers: Generated<number>;
  day: string;
  events: Generated<number>;
  name: string;
  org_id: string;
  sessions: Generated<number>;
  utm_source: Generated<string>;
  venue_key: Generated<string>;
}

export interface FactItemDaily {
  category: string | null;
  computed_at: Generated<Timestamp>;
  day: string;
  item_key: string;
  item_name: string;
  menu_item_id: string | null;
  orders: Generated<number>;
  org_id: string;
  qty: Generated<Numeric>;
  revenue_cents: Generated<number>;
  venue_id: string;
}

export interface FactSalesDaily {
  channel: TxnChannel;
  computed_at: Generated<Timestamp>;
  day: string;
  discount_cents: Generated<number>;
  discounted_orders: Generated<number>;
  gross_cents: Generated<number>;
  identified_gross_cents: Generated<number>;
  identified_orders: Generated<number>;
  items: Generated<Numeric>;
  net_cents: Generated<number>;
  new_customer_orders: Generated<number>;
  orders: Generated<number>;
  org_id: string;
  refunded_cents: Generated<number>;
  refunded_orders: Generated<number>;
  returning_customer_orders: Generated<number>;
  source: TxnSource;
  tax_cents: Generated<number>;
  tip_cents: Generated<number>;
  venue_id: string;
}

export interface FactSalesHourly {
  computed_at: Generated<Timestamp>;
  day: string;
  discount_cents: Generated<number>;
  discounted_orders: Generated<number>;
  gross_cents: Generated<number>;
  hour: number;
  identified_gross_cents: Generated<number>;
  identified_orders: Generated<number>;
  items: Generated<Numeric>;
  net_cents: Generated<number>;
  new_customer_orders: Generated<number>;
  orders: Generated<number>;
  org_id: string;
  refunded_cents: Generated<number>;
  refunded_orders: Generated<number>;
  returning_customer_orders: Generated<number>;
  tax_cents: Generated<number>;
  tip_cents: Generated<number>;
  venue_id: string;
}

export interface FeatureFlags {
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  expires_at: Timestamp;
  id: Generated<string>;
  key: string;
  org_id: string | null;
  owner: string;
}

export interface FlowEnrollments {
  completed_at: Timestamp | null;
  context: Generated<Json>;
  customer_id: string;
  cycle: Generated<number>;
  enrolled_at: Generated<Timestamp>;
  flow_id: string;
  id: Generated<string>;
  next_at: Timestamp | null;
  org_id: string;
  status: Generated<EnrollmentStatus>;
  step: Generated<number>;
  venue_id: string | null;
}

export interface Flows {
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  key: string;
  mode: Generated<FlowMode>;
  name: string;
  offer_id: string | null;
  org_id: string;
  template_version: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface HourExceptions {
  closed: Generated<boolean>;
  closes_at: string | null;
  created_at: Generated<Timestamp>;
  date: string;
  id: Generated<string>;
  opens_at: string | null;
  org_id: string;
  reason: string | null;
  venue_id: string;
}

export interface IngestCursors {
  connection_id: string;
  cursor: string | null;
  last_count: number | null;
  last_run_at: Timestamp | null;
  org_id: string;
  stream: string;
  synced_through: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface InsightDigests {
  generated_at: Generated<Timestamp>;
  id: Generated<string>;
  org_id: string;
  payload: Json;
  period: string;
  period_end: string;
  period_start: string;
  summary: string;
  venue_id: string | null;
}

export interface ItemModifierGroups {
  group_id: string;
  item_id: string;
  org_id: string;
  sort_order: Generated<number>;
}

export interface Jobs {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  finished_at: Timestamp | null;
  id: Generated<string>;
  idempotency_key: string | null;
  kind: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  org_id: string | null;
  payload: Generated<Json>;
  payload_version: Generated<number>;
  run_at: Generated<Timestamp>;
  status: Generated<JobStatus>;
}

export interface KitchenTickets {
  acknowledged_at: Timestamp | null;
  allergen_flags: Generated<string[]>;
  bumped_at: Timestamp | null;
  channel: OrderChannel;
  first_viewed_at: Timestamp | null;
  guest_name: string | null;
  id: Generated<string>;
  notes: string | null;
  order_id: string;
  org_id: string;
  ready_at: Timestamp | null;
  received_at: Generated<Timestamp>;
  service_date: string;
  status: Generated<TicketStatus>;
  table_label: string | null;
  target_ready_at: Timestamp | null;
  ticket_number: number;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface LlmUsage {
  day: string;
  id: Generated<string>;
  input_tokens: number;
  model: string;
  occurred_at: Generated<Timestamp>;
  org_id: string;
  outcome: string;
  output_tokens: number;
  purpose: string;
  tier: string;
}

export interface LoyaltyAccounts {
  customer_id: string;
  enrolled_at: Generated<Timestamp>;
  enrolled_venue_id: string | null;
  id: Generated<string>;
  member_code: string;
  org_id: string;
  program_id: string;
  status: Generated<string>;
  tier_id: string | null;
}

export interface LoyaltyPrograms {
  birthday_bonus: Generated<number>;
  created_at: Generated<Timestamp>;
  earn_model: Generated<string>;
  enrolment_bonus: Generated<number>;
  expiry_months: number | null;
  expiry_policy: Generated<string>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  org_id: string;
  point_value_cents: Generated<Numeric>;
  points_per_dollar: Generated<Numeric>;
  points_rounding: Generated<string>;
  terms_url: string | null;
  updated_at: Generated<Timestamp>;
}

export interface LoyaltyTiers {
  id: Generated<string>;
  multiplier: Generated<Numeric>;
  name: string;
  org_id: string;
  perks: Generated<Json>;
  program_id: string;
  sort_order: Generated<number>;
  threshold_points: Generated<number>;
  threshold_window_months: Generated<number>;
}

export interface LoyaltyTransactions {
  account_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  idempotency_key: string;
  kind: LoyaltyTxnKind;
  note: string | null;
  occurred_at: Generated<Timestamp>;
  order_id: string | null;
  org_id: string;
  points: number;
  redemption_id: string | null;
  source_transaction_id: string | null;
  staff_id: string | null;
  venue_id: string | null;
}

export interface Media {
  alt: string | null;
  bytes: number | null;
  content_type: string | null;
  created_at: Generated<Timestamp>;
  height: number | null;
  id: Generated<string>;
  kind: Generated<string>;
  org_id: string;
  storage_key: string;
  url: string;
  width: number | null;
}

export interface MenuImports {
  confirmed_by_staff_id: string | null;
  confirmed_item_count: Generated<number>;
  created_at: Generated<Timestamp>;
  created_by_staff_id: string | null;
  error: string | null;
  extracted: Json | null;
  id: Generated<string>;
  model: string | null;
  org_id: string;
  source_chars: number | null;
  source_kind: string;
  source_ref: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface MenuItems {
  allergens: Generated<string[]>;
  calories: number | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  dietary_tags: Generated<string[]>;
  id: Generated<string>;
  image_url: string | null;
  is_alcohol: Generated<boolean>;
  is_available: Generated<boolean>;
  is_visible_in_venue: Generated<boolean>;
  is_visible_online: Generated<boolean>;
  max_per_order: number | null;
  name: string;
  org_id: string;
  pos_catalog_id: string | null;
  prep_minutes: Generated<number>;
  price_cents: number;
  section_id: string;
  sort_order: Generated<number>;
  spice_level: number | null;
  unavailable_until: Timestamp | null;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface Menus {
  available_days: Generated<number[]>;
  available_from: string | null;
  available_to: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  org_id: string;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface MenuSections {
  deleted_at: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  is_visible: Generated<boolean>;
  menu_id: string;
  name: string;
  org_id: string;
  sort_order: Generated<number>;
  venue_id: string;
}

export interface MessageEvents {
  event: string;
  id: Generated<string>;
  message_id: string;
  metadata: Generated<Json>;
  occurred_at: Generated<Timestamp>;
  org_id: string;
}

export interface Messages {
  attempts: Generated<number>;
  campaign_id: string | null;
  channel: MsgChannel;
  cost_cents: number | null;
  customer_id: string | null;
  delivered_at: Timestamp | null;
  error: string | null;
  flow_id: string | null;
  from_identity_id: string | null;
  id: Generated<string>;
  idempotency_key: string;
  kind: MsgKind;
  next_attempt_at: Timestamp | null;
  org_id: string;
  payload: Generated<Json>;
  provider: string | null;
  provider_message_id: string | null;
  queued_at: Generated<Timestamp>;
  rendered_body: string | null;
  sent_at: Timestamp | null;
  status: Generated<MsgStatus>;
  subject: string | null;
  template_key: string;
  to_address: string;
  venue_id: string | null;
}

export interface ModifierGroups {
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_required: Generated<boolean>;
  max_selections: Generated<number>;
  min_selections: Generated<number>;
  name: string;
  org_id: string;
  selection_type: Generated<SelectionType>;
  sort_order: Generated<number>;
  venue_id: string;
}

export interface Modifiers {
  deleted_at: Timestamp | null;
  group_id: string;
  id: Generated<string>;
  is_available: Generated<boolean>;
  is_default: Generated<boolean>;
  name: string;
  org_id: string;
  price_delta_cents: Generated<number>;
  sort_order: Generated<number>;
  venue_id: string;
}

export interface OfferCodes {
  claimed_at: Timestamp | null;
  code: string;
  customer_id: string | null;
  discount_applied_cents: number | null;
  expires_at: Timestamp;
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  offer_id: string;
  org_id: string;
  redeemed_at: Timestamp | null;
  redeemed_order_id: string | null;
  redeemed_transaction_id: string | null;
  redeemed_venue_id: string | null;
  source: string | null;
  status: Generated<OfferCodeStatus>;
  void_reason: string | null;
  voided_at: Timestamp | null;
}

export interface Offers {
  campaign_id: string | null;
  channels: Generated<ArrayType<OrderChannel>>;
  code_prefix: Generated<string>;
  created_at: Generated<Timestamp>;
  creator_id: string | null;
  description: string | null;
  discount_kind: DiscountKind;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: OfferKind;
  max_codes: number | null;
  menu_item_id: string | null;
  min_spend_cents: Generated<number>;
  name: string;
  org_id: string;
  percent_off: number | null;
  price_cents: Generated<number>;
  requires_claim: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  valid_venue_ids: string[] | null;
  validity_days: Generated<number>;
  value_cents: number | null;
}

export interface Onboardings {
  confirmations: Generated<Json>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  intake: Generated<Json>;
  intake_progress: Generated<Json>;
  intake_version: Generated<number>;
  live_at: Timestamp | null;
  manual_touch_minutes: Generated<number>;
  org_id: string | null;
  origin: Generated<OnboardingOrigin>;
  sold_at: Generated<Timestamp>;
  started_by_user_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface OnboardingTouches {
  admin_user_id: string | null;
  id: Generated<string>;
  minutes: number;
  note: string;
  onboarding_id: string;
  recorded_at: Generated<Timestamp>;
}

export interface OrderItems {
  allergens: Generated<string[]>;
  category_snapshot: string | null;
  id: Generated<string>;
  is_alcohol: Generated<boolean>;
  line_no: Generated<number>;
  line_total_cents: number;
  menu_item_id: string | null;
  modifier_ids: Generated<string[]>;
  modifiers: Generated<Json>;
  name_snapshot: string;
  note: string | null;
  order_id: string;
  org_id: string;
  prep_minutes: Generated<number>;
  qty: number;
  unit_price_cents: number;
}

export interface Orders {
  absorbed_codes: Generated<string[]>;
  absorbed_discount_cents: Generated<number>;
  accepted_at: Timestamp | null;
  adjustments: Generated<Json>;
  attention_at: Timestamp | null;
  attention_reason: string | null;
  cancelled_at: Timestamp | null;
  channel: OrderChannel;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  customer_email: string | null;
  customer_id: string | null;
  customer_name: string | null;
  customer_note: string | null;
  customer_phone: string | null;
  delivery_fee_cents: Generated<number>;
  discount_cents: Generated<number>;
  flags: Generated<string[]>;
  id: Generated<string>;
  idempotency_key: string;
  item_count: Generated<number>;
  loyalty_redemption_id: string | null;
  offer_code_id: string | null;
  org_id: string;
  payment_status: Generated<OrderPaymentStatus>;
  pickup_slot_end: Timestamp | null;
  pickup_slot_start: Timestamp | null;
  placed_at: Timestamp | null;
  pos_order_ref: string | null;
  promised_at: Timestamp | null;
  promo_code: string | null;
  qr_code_id: string | null;
  ready_at: Timestamp | null;
  reference: string;
  rejected_reason: string | null;
  requested_asap: Generated<boolean>;
  session_id: string | null;
  status: Generated<OrderStatus>;
  subtotal_cents: Generated<number>;
  table_label: string | null;
  table_session_id: string | null;
  tax_cents: Generated<number>;
  tip_cents: Generated<number>;
  total_cents: Generated<number>;
  tracking_token: string | null;
  transaction_id: string | null;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface OrderStatusHistory {
  at: Generated<Timestamp>;
  by_id: string | null;
  by_kind: string;
  from_status: OrderStatus | null;
  id: Generated<string>;
  order_id: string;
  org_id: string;
  reason: string | null;
  to_status: OrderStatus;
}

export interface Orgs {
  abn: string | null;
  benchmark_opt_in: Generated<boolean>;
  country: Generated<string>;
  created_at: Generated<Timestamp>;
  cuisine_tags: Generated<string[]>;
  currency: Generated<string>;
  id: Generated<string>;
  legal_name: string;
  plan: Generated<string>;
  price_band: number | null;
  settings: Generated<Json>;
  slug: string;
  status: Generated<OrgStatus>;
  tax_inclusive: Generated<boolean>;
  tax_rate_bp: Generated<number>;
  timezone: Generated<string>;
  trading_name: string;
  updated_at: Generated<Timestamp>;
}

export interface OtpCodes {
  attempts: Generated<number>;
  code_hash: Buffer;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  destination: string;
  expires_at: Timestamp;
  id: Generated<string>;
  org_id: string | null;
  purpose: OtpPurpose;
}

export interface Pages {
  blocks: Generated<Json>;
  created_at: Generated<Timestamp>;
  draft: Json | null;
  id: Generated<string>;
  og_image_url: string | null;
  org_id: string;
  published_at: Timestamp | null;
  seo_description: string | null;
  seo_title: string | null;
  slug: string;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
  venue_id: string | null;
}

export interface Payments {
  amount_cents: number;
  card_brand: string | null;
  card_last4: string | null;
  checked_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  external_ref: string | null;
  failure_reason: string | null;
  id: Generated<string>;
  idempotency_key: string;
  order_id: string | null;
  org_id: string;
  provider: string;
  raw: Json | null;
  refunded_cents: Generated<number>;
  status: Generated<PaymentStatus>;
  tip_cents: Generated<number>;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface PlatformAdmins {
  created_at: Generated<Timestamp>;
  role: Generated<string>;
  user_id: string;
}

export interface PlugReviews {
  plug_key: string;
  reviewed_at: Generated<Timestamp>;
  reviewed_by: string;
  tool_list: Json;
  tools_digest: string;
}

export interface ProvisioningSteps {
  attempts: Generated<number>;
  blocked_on: string | null;
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  onboarding_id: string;
  org_id: string | null;
  result: Json | null;
  started_at: Timestamp | null;
  status: Generated<string>;
  step: string;
}

export interface QrCodes {
  area: string | null;
  campaign_id: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  creator_id: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  kind: QrKind;
  label: string | null;
  last_scanned_at: Timestamp | null;
  offer_id: string | null;
  org_id: string;
  print_batch: string | null;
  scan_count: Generated<number>;
  target_path: Generated<string>;
  venue_id: string;
}

export interface RateLimits {
  count: Generated<number>;
  key: string;
  window_start: Timestamp;
}

export interface Redemptions {
  account_id: string;
  channel: Generated<RedemptionChannel>;
  code: string;
  discount_cents: number | null;
  expires_at: Timestamp;
  force_reason: string | null;
  forced: Generated<boolean>;
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  issued_staff_id: string | null;
  issued_venue_id: string | null;
  order_id: string | null;
  org_id: string;
  points: number;
  redeemed_at: Timestamp | null;
  redeemed_staff_id: string | null;
  redeemed_venue_id: string | null;
  reward_id: string;
  status: Generated<RedemptionStatus>;
  transaction_id: string | null;
  void_reason: string | null;
  voided_at: Timestamp | null;
}

export interface Redirects {
  created_at: Generated<Timestamp>;
  from_path: string;
  hits: Generated<number>;
  id: Generated<string>;
  org_id: string;
  status_code: Generated<number>;
  to_path: string;
}

export interface Refunds {
  amount_cents: number;
  checked_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  external_ref: string | null;
  failure_reason: string | null;
  id: Generated<string>;
  idempotency_key: string;
  order_id: string | null;
  org_id: string;
  payment_id: string;
  reason: string;
  staff_id: string | null;
  status: Generated<PaymentStatus>;
  updated_at: Generated<Timestamp>;
}

export interface ReviewListingInsights {
  calls: Generated<number>;
  connection_id: string;
  day: string;
  directions: Generated<number>;
  org_id: string;
  searches: Generated<number>;
  updated_at: Generated<Timestamp>;
  venue_id: string;
  website_clicks: Generated<number>;
}

export interface ReviewReplyDrafts {
  agent_run_id: string | null;
  approval_id: string | null;
  approved_by_staff_id: string | null;
  author: ReviewDraftAuthor;
  blocked_reasons: Generated<string[]>;
  body: string;
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  created_by_kind: string;
  decided_at: Timestamp | null;
  error: string | null;
  id: Generated<string>;
  org_id: string;
  posted_at: Timestamp | null;
  review_id: string;
  status: ReviewDraftStatus;
  template_version: string | null;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface Reviews {
  author_name: string | null;
  body: string | null;
  connection_id: string | null;
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  external_id: string;
  id: Generated<string>;
  org_id: string;
  rating: number | null;
  raw: Json | null;
  replied_at: Timestamp | null;
  reply_body: string | null;
  reply_status: Generated<ReviewReplyStatus>;
  reviewed_at: Timestamp;
  source: string;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface ReviewSyncState {
  connection_id: string;
  cursor: string | null;
  insights_through: string | null;
  last_count: number | null;
  last_error: string | null;
  last_run_at: Timestamp | null;
  org_id: string;
  synced_through: Timestamp | null;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface Rewards {
  cost_points: number;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  image_url: string | null;
  is_active: Generated<boolean>;
  kind: DiscountKind;
  max_redemptions_per_customer: number | null;
  max_redemptions_total: number | null;
  menu_item_id: string | null;
  min_spend_cents: Generated<number>;
  name: string;
  org_id: string;
  percent_off: number | null;
  program_id: string;
  valid_days: number[] | null;
  valid_from: Timestamp | null;
  valid_to: Timestamp | null;
  valid_venue_ids: string[] | null;
  value_cents: number | null;
}

export interface RollupState {
  computed_at: Generated<Timestamp>;
  day: string;
  org_id: string;
  rollup: string;
  signature: string | null;
  source_max_ingested_at: Timestamp | null;
}

export interface SavedViews {
  created_at: Generated<Timestamp>;
  created_by_id: string | null;
  created_by_kind: Generated<string>;
  description: string | null;
  id: Generated<string>;
  is_pinned: Generated<boolean>;
  name: string;
  org_id: string;
  query: Json;
  updated_at: Generated<Timestamp>;
}

export interface Secrets {
  ciphertext: Buffer;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  key_version: Generated<number>;
  nonce: Buffer;
  org_id: string;
  purpose: string;
  rotated_at: Timestamp | null;
}

export interface Segments {
  created_at: Generated<Timestamp>;
  definition: Json;
  description: string | null;
  id: Generated<string>;
  is_system: Generated<boolean>;
  name: string;
  org_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SendingIdentities {
  channel: MsgChannel;
  created_at: Generated<Timestamp>;
  dns_records: Json | null;
  domain: string | null;
  from_email: string | null;
  from_name: string | null;
  id: Generated<string>;
  kind: MsgKind;
  org_id: string;
  provider: string;
  provider_domain_id: string | null;
  sms_sender_id: string | null;
  status: Generated<string>;
  verified_at: Timestamp | null;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  customer_id: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  kind: SessionKind;
  last_seen_at: Timestamp | null;
  org_id: string | null;
  revoked_at: Timestamp | null;
  token_hash: Buffer;
  user_agent: string | null;
  user_id: string | null;
}

export interface SideEffects {
  created_at: Generated<Timestamp>;
  error: string | null;
  id: Generated<string>;
  key: string;
  kind: string;
  org_id: string;
  result: Json | null;
  status: Generated<SideEffectStatus>;
  updated_at: Generated<Timestamp>;
}

export interface Staff {
  created_at: Generated<Timestamp>;
  email: string;
  first_name: string;
  id: Generated<string>;
  is_owner: Generated<boolean>;
  last_name: string | null;
  org_id: string;
  phone: string | null;
  status: Generated<StaffStatus>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface StaffVenues {
  org_id: string;
  role: StaffRole;
  staff_id: string;
  venue_id: string;
}

export interface SupportAccess {
  admin_user_id: string;
  ended_at: Timestamp | null;
  id: Generated<string>;
  org_id: string;
  reason: string;
  started_at: Generated<Timestamp>;
}

export interface Suppressions {
  channel: MsgChannel;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  org_id: string;
  reason: SuppressionReason;
  value: string;
}

export interface TableSessions {
  closed_at: Timestamp | null;
  covers: number | null;
  id: Generated<string>;
  last_activity_at: Generated<Timestamp>;
  opened_at: Generated<Timestamp>;
  org_id: string;
  qr_code_id: string | null;
  table_label: string;
  venue_id: string;
}

export interface Templates {
  body: string;
  channel: MsgChannel;
  id: Generated<string>;
  is_active: Generated<boolean>;
  org_id: string | null;
  subject: string | null;
  template_key: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface TicketEvents {
  device_id: string | null;
  event: string;
  id: Generated<string>;
  idempotency_key: string;
  metadata: Generated<Json>;
  occurred_at: Generated<Timestamp>;
  org_id: string;
  seq: Generated<number>;
  staff_id: string | null;
  ticket_id: string;
}

export interface TradingHours {
  closes_at: string;
  day_of_week: number;
  id: Generated<string>;
  opens_at: string;
  org_id: string;
  service_type: Generated<string>;
  venue_id: string;
}

export interface TransactionAttributions {
  attributed_at: Generated<Timestamp>;
  campaign_id: string | null;
  channel: string | null;
  code: string | null;
  confidence: Generated<Numeric>;
  creator_id: string | null;
  customer_id: string | null;
  id: Generated<string>;
  model: string;
  model_version: Generated<number>;
  org_id: string;
  transaction_id: string;
}

export interface TransactionLines {
  category_snapshot: string | null;
  discount_cents: Generated<number>;
  id: Generated<string>;
  line_no: number;
  menu_item_id: string | null;
  modifiers: Generated<Json>;
  name_snapshot: string;
  org_id: string;
  qty: Generated<Numeric>;
  tax_cents: Generated<number>;
  total_cents: Generated<number>;
  transaction_id: string;
  unit_price_cents: Generated<number>;
}

export interface Transactions {
  channel: TxnChannel;
  currency: Generated<string>;
  customer_id: string | null;
  discount_cents: Generated<number>;
  external_ref: string;
  id: Generated<string>;
  ingested_at: Generated<Timestamp>;
  occurred_at: Timestamp;
  order_id: string | null;
  org_id: string;
  raw: Json | null;
  refunded_cents: Generated<number>;
  source: TxnSource;
  staff_ref: string | null;
  status: Generated<TxnStatus>;
  subtotal_cents: Generated<number>;
  table_label: string | null;
  tax_cents: Generated<number>;
  tender_type: string | null;
  tip_cents: Generated<number>;
  total_cents: number;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string | null;
  phone: string | null;
  totp_secret_ref: string | null;
}

export interface VenueModules {
  config: Generated<Json>;
  config_version: Generated<number>;
  enabled: Generated<boolean>;
  enabled_at: Timestamp | null;
  module_key: string;
  org_id: string;
  updated_at: Generated<Timestamp>;
  venue_id: string;
}

export interface Venues {
  address_line1: string | null;
  address_line2: string | null;
  capacity: number | null;
  created_at: Generated<Timestamp>;
  cuisine_tags: Generated<string[]>;
  email: string | null;
  id: Generated<string>;
  lat: number | null;
  lng: number | null;
  name: string;
  opened_at: string | null;
  org_id: string;
  phone: string | null;
  postcode: string | null;
  price_band: number | null;
  settings: Generated<Json>;
  slug: string;
  state: string | null;
  status: Generated<VenueStatus>;
  suburb: string | null;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface VisitorSessions {
  campaign_id: string | null;
  code: string | null;
  creator_id: string | null;
  customer_id: string | null;
  device_class: string | null;
  first_seen_at: Generated<Timestamp>;
  id: string;
  landing_path: string | null;
  last_seen_at: Generated<Timestamp>;
  org_id: string;
  qr_code_id: string | null;
  referrer: string | null;
  utm_campaign: string | null;
  utm_content: string | null;
  utm_medium: string | null;
  utm_source: string | null;
  venue_id: string | null;
}

export interface WebhookEvents {
  connection_id: string | null;
  error: string | null;
  event_id: string;
  event_type: string | null;
  id: Generated<string>;
  org_id: string | null;
  payload_digest: string | null;
  processed_at: Timestamp | null;
  provider: string;
  received_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface DB {
  ad_conversions: AdConversions;
  agent_calls: AgentCalls;
  agent_confirmations: AgentConfirmations;
  agent_keys: AgentKeys;
  agent_oauth_clients: AgentOauthClients;
  agent_oauth_codes: AgentOauthCodes;
  agent_oauth_tokens: AgentOauthTokens;
  agent_runs: AgentRuns;
  approvals: Approvals;
  audit_log: AuditLog;
  benchmark_bands: BenchmarkBands;
  brands: Brands;
  campaigns: Campaigns;
  connections: Connections;
  consent_events: ConsentEvents;
  consent_wordings: ConsentWordings;
  consents: Consents;
  customer_identities: CustomerIdentities;
  customer_merges: CustomerMerges;
  customer_touchpoints: CustomerTouchpoints;
  customers: Customers;
  deliveries: Deliveries;
  delivery_status_history: DeliveryStatusHistory;
  delivery_zones: DeliveryZones;
  devices: Devices;
  domains: Domains;
  esp_sync_profiles: EspSyncProfiles;
  esp_sync_state: EspSyncState;
  events: Events;
  fact_campaign_daily: FactCampaignDaily;
  fact_customer: FactCustomer;
  fact_events_daily: FactEventsDaily;
  fact_item_daily: FactItemDaily;
  fact_sales_daily: FactSalesDaily;
  fact_sales_hourly: FactSalesHourly;
  feature_flags: FeatureFlags;
  flow_enrollments: FlowEnrollments;
  flows: Flows;
  hour_exceptions: HourExceptions;
  ingest_cursors: IngestCursors;
  insight_digests: InsightDigests;
  item_modifier_groups: ItemModifierGroups;
  jobs: Jobs;
  kitchen_tickets: KitchenTickets;
  llm_usage: LlmUsage;
  loyalty_accounts: LoyaltyAccounts;
  loyalty_programs: LoyaltyPrograms;
  loyalty_tiers: LoyaltyTiers;
  loyalty_transactions: LoyaltyTransactions;
  media: Media;
  menu_imports: MenuImports;
  menu_items: MenuItems;
  menu_sections: MenuSections;
  menus: Menus;
  message_events: MessageEvents;
  messages: Messages;
  modifier_groups: ModifierGroups;
  modifiers: Modifiers;
  offer_codes: OfferCodes;
  offers: Offers;
  onboarding_touches: OnboardingTouches;
  onboardings: Onboardings;
  order_items: OrderItems;
  order_status_history: OrderStatusHistory;
  orders: Orders;
  orgs: Orgs;
  otp_codes: OtpCodes;
  pages: Pages;
  payments: Payments;
  platform_admins: PlatformAdmins;
  plug_reviews: PlugReviews;
  provisioning_steps: ProvisioningSteps;
  qr_codes: QrCodes;
  rate_limits: RateLimits;
  redemptions: Redemptions;
  redirects: Redirects;
  refunds: Refunds;
  review_listing_insights: ReviewListingInsights;
  review_reply_drafts: ReviewReplyDrafts;
  review_sync_state: ReviewSyncState;
  reviews: Reviews;
  rewards: Rewards;
  rollup_state: RollupState;
  saved_views: SavedViews;
  secrets: Secrets;
  segments: Segments;
  sending_identities: SendingIdentities;
  sessions: Sessions;
  side_effects: SideEffects;
  staff: Staff;
  staff_venues: StaffVenues;
  support_access: SupportAccess;
  suppressions: Suppressions;
  table_sessions: TableSessions;
  templates: Templates;
  ticket_events: TicketEvents;
  trading_hours: TradingHours;
  transaction_attributions: TransactionAttributions;
  transaction_lines: TransactionLines;
  transactions: Transactions;
  users: Users;
  venue_modules: VenueModules;
  venues: Venues;
  visitor_sessions: VisitorSessions;
  webhook_events: WebhookEvents;
}
